---
skip_tags: true
branches:
  only:
    - master
image: "Visual Studio 2017"
build_script:
  - ps: ./test.ps1
on_finish:
  - ps: ./kill.ps1
environment:
  DOTokenSecure:
    secure: Tk+kQ8w/Xy+Z3xzIH03Ml4lw+5LL3eXvFwV3fXilBTVD+R/JrgUH9VgGnVazoU1HcvFjcpQ8Tlmg37E/hqHfcocPQoxmRpCcEzeanBITYeU=