---
skip_tags: true
branches:
  only:
    - master
image: "Windows Server 2019"
build_script:
  - ps: ./test.ps1
on_finish:
  - ps: ./kill.ps1
environment:
  DOTokenSecure:
    secure: AUw58w59H5g0wTMdspmDKkdMBEll32LD6rLfBFyaGorRq1o876uiP40imfsze6xHc9Q3sUbLeYeOH7hbXQwkWunQYyS6sReF9WTh+oHLwbE=
